name: aur-nonfree-sorah
package_key: 17C611F16D92677398E0ADF51AD43CA09D82C624
repo_key: 17C611F16D92677398E0ADF51AD43CA09D82C624
srcdest: sources
logdest: logs
pkgbuild: PKGBUILDs
builds:
  x86_64:
      chroot: ../archroot/x86_64
s3:
  region: ap-northeast-1
  bucket: arch.sorah.jp
